# Generated by Django 4.2 on 2023-04-20 01:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('tgbot', '0002_image_date'), ('tgbot', '0003_rename_date_image_datetime_alter_profile_name'), ('tgbot', '0004_rename_image_id_image_file_id_and_more'), ('tgbot', '0005_rename_user_imagescore_profile_and_more')]

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(default='', verbose_name='Имя пользователя'),
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_id',
            new_name='file_id',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_unique_id',
            new_name='file_unique_id',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_hash',
            new_name='phash',
        ),
        migrations.RenameField(
            model_name='imagescore',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='imagescore',
            unique_together={('profile', 'image')},
        ),
    ]
