# Generated by Django 4.2 on 2023-04-20 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_image_date_squashed_0005_rename_user_imagescore_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='tgbot.profile', verbose_name='Профиль владельца'),
        ),
        migrations.AlterField(
            model_name='imagescore',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_score', to='tgbot.image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imagescore',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_score', to='tgbot.profile', verbose_name='Пользователь'),
        ),
    ]
