# Generated by Django 4.2 on 2023-04-24 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_alter_image_datetime_alter_image_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='profile',
            name='last_bot_message',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Сообщение от бота'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Активность пользователя'),
        ),
    ]
