# Generated by Django 4.2 on 2023-05-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image_file',
            field=models.BinaryField(blank=True, verbose_name='Дата взаимодействия'),
        ),
    ]
