# Generated by Django 4.2 on 2023-05-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('tgbot', '0013_alter_report_options_alter_report_unique_together'), ('tgbot', '0014_alter_imageblock_image'), ('tgbot', '0015_alter_imageblock_image')]

    dependencies = [
        ('tgbot', '0012_imageblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Жалоба', 'verbose_name_plural': 'Жалобы'},
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('profile', 'image')},
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='tgbot.image', verbose_name='Изображение'),
        ),
    ]
