# Generated by Django 4.2 on 2023-05-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0013_alter_report_options_alter_report_unique_together_squashed_0015_alter_imageblock_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='image_file',
        ),
    ]
