# Generated by Django 4.2 on 2023-05-15 13:03

from django.db import migrations, models
import django.db.models.deletion
import tgbot.models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0016_remove_report_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.TextField(unique=True, verbose_name='Идентификатор изображения')),
                ('image_message_id', models.IntegerField(verbose_name='Идентификатор сообщения пользователя')),
                ('response_message_id', models.IntegerField(verbose_name='Идентификатор сообщения ответа')),
                ('datetime', models.DateTimeField(default=tgbot.models.datetime_now, verbose_name='Дата взаимодействия')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_upload_cache', to='tgbot.profile', verbose_name='Профиль владельца')),
            ],
        ),
    ]
