# Generated by Django 4.2 on 2023-05-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0017_imageuploadcache'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUploadCache',
        ),
    ]
